README.md

Add a missing comma `,` to the example code to make it works.

fix README example typo

---

lua/formatter/format.lua

After upgrading the plugin, `prettier` kept failing to run, I tracked down the changes & it seems that in the latest changes here https://github.com/mhartington/formatter.nvim/commit/6cc7d40b7fe0d82e4fe4cd1adc5553e0c9646969 it introduced a  change in the way the `cmd` was passed to `jobstart` from a string https://github.com/mhartington/formatter.nvim/blob/87e2de66779d0e857ba2993b20bbcd0cbc1bfc6d/lua/formatter/format.lua#L90-L94 to a table https://github.com/mhartington/formatter.nvim/blob/6cc7d40b7fe0d82e4fe4cd1adc5553e0c9646969/lua/formatter/format.lua#L109 https://github.com/mhartington/formatter.nvim/blob/6cc7d40b7fe0d82e4fe4cd1adc5553e0c9646969/lua/formatter/format.lua#L95-L100
This PR keeps the old behaviour of passing a string, which is according to the `:h jobstart()` is the right …

Pass cmd as a string to jobstart

---

lua/formatter/util.lua

I ran into this error while formatting a markdown file:
Before:
```
$x$ 
$x + y$
```
After:
```
$x$ $x + y$
```
This would cause an index out of bounds error since the `util.setLines` function is trying to set lines which don't exist anymore i.e. the second line. 
In the documentation for `nvim_buf_set_lines` we can read:
```
nvim_buf_set_lines({buffer}, {start}, {end}, {strict_indexing}, {replacement})
...
Out-of-bounds indices are clamped to the nearest valid value,
unless `strict_indexing` is set.
```
Which was indeed previously set to true and therefore caused errors.
Do note that I don't know enough of this function to confidently say setting `strict_indexing` to `false` doesn't cause any unforeseen side effects so I'd advice the maintainers to take a look at that.
For reproducing …

Fix: Index out of bounds

---

lua/formatter/util.lua

This code is from [plenary.nvim](https://github.com/nvim-lua/plenary.nvim/blob/8bae2c1fadc9ed5bfcfb5ecbd0c0c4d7d40cb974/lua/plenary/path.lua#L20-L31)

fix(util): use os path separator closes #60

---

CONFIG.md

The "-" argument must be provided to the terraform fmt command in order to read from STDIN. From `terraform fmt -h`:
If DIR is not specified then the current working directory will be used.
If DIR is "-" then content will be read from STDIN. The given content must
be in the Terraform language native syntax; JSON is not supported.

docs: add config for terraform fmt

---

lua/formatter/config.lua
lua/formatter/format.lua
lua/formatter/util.lua

This adds some better logging logic. 
Making use of neovim's own internal log levels, we can only print to the log area if the users asks for it.
```lua
vim.log = {
levels = {
TRACE = 0;
DEBUG = 1;
INFO  = 2;
WARN  = 3;
ERROR = 4;
}
}
```
Based on these default values, we can ask users to enable logging if they want it.
```
formatter.setup(
{
logging = true,
log_level = 2,
filetype = formatterConfig
}
)
```
This will make the `logging` option no long needed. 
If they do not want any logging, they can simply leave out the `log_level` from their setup function, and they will not have any.
If they need to debug issues, they can set the appropriate level in the setup function.
This will allow the plugin to set appropriate logs internally and not worry about annoying users.

add some better logging logic

---

CONFIG.md

A config for the latexindent perl script that ships with texlive, works on linux, should work on mac. I think it should work on windows too as latexindent ships as an exe with miktex but I've not tested. See https://github.com/cmhughes/latexindent.pl for details.

Add config for latexindent

---

lua/formatter/format.lua
plugin/formatter.vim

Separate PR created from #109 for converting `write` to an opts table to make it easy to extend in the future.

Converts optional parameters to a table

---

CONFIG.md

`rustfmt` defaults to 2015 edition which doesn't not know anything about eg `async fn` syntax. The formatter then fails silently without any clue in `:messages`, so it took me some time, digging into the formatter source, before running `rustfmt` by hands and getting the error. Pinning the last edition obviously isn't perfect, as people work on legacy projects, but I believe removing the arg much easier than finding one to add :)
Would it worth adding into `:messages` something like: "an error occurred while calling `rustfmt --emit=stdout main.rs`, run the command by hands to see the error details"?

Add `--edition` arg to `rustfmt`

---

CONFIG.md

Introduced HCL Formatter for `*.hcl` filetype.
- https://github.com/gruntwork-io/terragrunt/issues/1037#issuecomment-583057827
- https://terragrunt.gruntwork.io/docs/getting-started/configuration/#formatting-hcl-files

Added HCL formatter

---

README.md
doc/formatter.txt
lua/formatter/format.lua
lua/formatter/log.lua
lua/formatter/util.lua

Use `silent` on pre/post format hooks only when `log_level` is higher than `vim.log.levels.DEBUG`.
fixes #143

Pre/post hook log_level integration

---

lua/formatter/filetypes/json.lua

Fix the `jq` config.
- The args property should be a list; and
- `jq` should read from stdin.

fix(json.jq): fix jq config

---

README.md

Current URL does not point to anything. Add .lua filetype so it points to the correct file.

fix util.lua link in readme

---

lua/formatter/filetypes/sh.lua

It was inspired by [neoformat formatter for sh](https://github.com/sbdchd/neoformat/blob/master/autoload/neoformat/formatters/sh.vim)
To test it you need to install ``shfmt``, then create any sh or bash file.
E.g. I tested this on my own local script, copy-paste this.
```sh
#!/usr/bin/env bash
help() {
echo "Usage: extract [file]
Available file formats:
.tar
.tar.bz2
.tar.gz
.tbz2
.tgz
.bz2
.rar
.gz
.zip
.Z
.7z"
}
if [ -f "$1" ] ; then
case "$1" in
*.tar) tar xvf "$1" ;;
*.tar.bz2) tar xvjf "$1" ;;
*.tar.gz) tar xvzf "$1" ;;
*.tbz2) tar xvjf "$1" ;;
*.tgz) tar xvzf "$1" ;;
*.bz2) bunzip2 "$1" ;;
*.rar) rar x "$1" ;;
*.gz) gunzip "$1" ;;
*.zip) unzip "$1" ;;
*.Z) uncompress "$1" ;;
*.7z) 7z x "$1" ;;
*) echo "'$1' cannot be extracted via extract()" && help ;;
esac
else
help
fi
```

Add sh filetype with shfmt formatter.

---

lua/formatter/config.lua

The `logging` configuration option was always
replaced by the default value when set to `false`.
I have to say though that I'm not even sure why this line
was needed, since the defaults are already copied from the
`default_config` when instantiating the `normalized` config.

fix: Preserve logging config if specified.

---

lua/formatter/filetypes/haskell.lua

Unfortunately, stylish-haskell doesn't have a flag like `--stdin-filepath` for passing path to the file passed to stdin, so it doesn't look for a config relative to a saved file.

Add haskell filetype with stylish-haskell

---

lua/formatter/filetypes/cmake.lua

cmake-format read from stdin by add `-` before inputfile
fix: #168 
reference: https://github.com/cheshirekow/cmake_format/issues/30#issuecomment-380167572

fix: stdin arg in cmake-format

---

lua/formatter/defaults/latexindent.lua
lua/formatter/filetypes/latex.lua

Created `latexindent.lua` in `defaults/` for the formatter and `latex.lua` in `filetypes/` that uses the default formatter.

Add latex support (with latexindent)

---

lua/formatter/defaults/phpcbf.lua
lua/formatter/filetypes/php.lua

`phpcbf` returns a non-zero code by default, so the option `ignore_exitcode` is also set to `true` by default.

Add php support

---

lua/formatter/format.lua

After merging #207 I've tried to use it with the following config
`
require("formatter.filetypes.dart").dartformat({
line_length = 120
}),
`
But it has failed because with passing parameters we have started to have the final table instead of having a function to call. I've added a check if the config is a table use it instead of calling it. I couldn't understand why we are calling these functions every time before format, instead of running and storing all of them at the set-up

fix: If method is already called do not call it again

---

lua/formatter/defaults/sed.lua

In-place mode varies between GNU and BSD (incl. macOS) sed: GNU accepts e.g. -i.bak or -i; BSD wants -i .bak or -i ''. It's therefore difficult to invoke this in a cross-platform way as far as I know; you'd need to detect which one is being used or require that GNU sed is installed.
However, since the default behaviour of sed is to read from stdin and write to stdout, and formatter.nvim supports this behaviour quite straightforwardly, we can just do that instead.
Fixes #201

Use sed as a pipe (the default behaviour)

---

lua/formatter/filetypes/ruby.lua

I found that the rubocop formatter was always deleting the first line of the
file; it seems that this is because there might be a varying amount of output
before the line of `=====`.
Using the `--stderr` flag means that the linter warnings are effectively thrown away and so don't have to be trimmed out with a transform function.
I think this might fix #153 too.

Use `--stderr` flag for rubocop rather than parsing output

---

lua/formatter/defaults/clangformat.lua

Couldn't find an util for the indent size...

Add current buffer's indent to clang-format, as a default instead of 2

---

lua/formatter/filetypes/rust.lua

This enables the user to use the async fn keyword with rustfmt.
Related Issue: #220

Add --edition 2021 argument by default for rustfmt

---

lua/formatter/defaults/clangformat.lua

This reverts https://github.com/mhartington/formatter.nvim/pull/222.
Clang-format by default sets the style to `file`, where it will use a user-provided configuration file if it exists. This is expected default behavior. The above PR overwrites this default.
This change is consistent with the defaults provided in other vim formatters like `sbdchd/neoformat`:
https://github.com/sbdchd/neoformat/blob/891fad5829f91cbc3d0866f7abd028d233b8763e/autoload/neoformat/formatters/c.vim#L16

revert clang-format style arg

---

lua/formatter/defaults/ktlint.lua
lua/formatter/filetypes/kotlin.lua

Adding support for Kotlin through using [`ktlint`](https://github.com/pinterest/ktlint). I based the default formatter off of `clangformat.lua` and the filetype formatter off of `java.lua`. Let me know if there are any corrections that need to be made.

Add support for ktlint (Kotlin)

---

lua/formatter/format.lua
lua/formatter/util.lua

when having a split for a single buffer, if you do `FormatWrite`, the _other_ window will change its view (I would see it scroll to the top).
this PR solves this problem by handling _all_ windows views associated to current buffer, instead of just current window

save/restore views for all windows associated to buffer-being-formatted

---

lua/formatter/filetypes/python.lua

Adding support for ruff's formatting module. It's 99.9% black compliant and runs orders of magnitude faster.

Add support for `ruff format` in python.lua

---

lua/formatter/filetypes/eruby.lua

This adds support for [.erb files](https://github.com/ruby/erb) being formatted using [erb-formatter](https://github.com/nebulab/erb-formatter).

add support for .erb files using erb-formatter

---

lua/formatter/filetypes/sql.lua

Introduce a default configuration for `sqlfluff` inspired by [lua/null-ls/builtins/formatting/sqlfluff.lua](https://github.com/Carlosiano/null-ls.nvim/blob/main/lua/null-ls/builtins/formatting/sqlfluff.lua).

feat: add default configuration for sqlfluff

---

README.md
doc/formatter.txt
lua/formatter/format.lua
lua/formatter/util.lua

This implementation prepends `$PATH` with `node_modules/.bin` when running `try_node_modules` formatters. To avoid `node_modules` lookups on every format, the path to `node_modules` (or lack of thereof) will be stored in `b:formatter_node_modules`.

Implement try_node_modules

---

lua/formatter/filetypes/liquidsoap.lua

Liquidsoap is scripting language for creating media streams and more. It's got about [1.8k](https://github.com/search?type=code&q=NOT+is%3Afork+path%3A*.liq) (still counting!) script files on github.
We're in the process of adding much needed tooling for script developers with [tree sitter grammar](https://github.com/savonet/tree-sitter-liquidsoap) (supported in [nvim-tree-sitter](https://github.com/nvim-treesitter/nvim-treesitter/pull/5433)), [vscode/textmate syntax](https://github.com/savonet/vscode-liquidsoap) (hopefully to be used by [github-linguist](https://github.com/github-linguist/linguist/pull/6565) at some point!).
File type for vim was [added recently](https://github.com/vim/vim/commit/6b5efcdd8e976d2ab2554b22c4220c5e88de4717) and [backported to …

Add formatter for liquidsoap script.

---

lua/formatter/filetypes/any.lua

Hello! I ran across this when using Neovim in an environment where I didn't have sed, and thought that there was probably some simple implementation that didn't need to rely on any external binaries. I know sed is super common, but I figured this might be a useful add for anyone looking for this specific functionality. I took close care to make sure that this would not affect search history and would behave as similarly as possible to the sed implementation.
Open to different function naming, and happy to make any changes needed.
Thanks for considering!

Add vim native trailing whitespace removal

---

lua/formatter/format.lua

If a formatter doesn't return anything, this results in a `current_output` value being `nil`. When passed to vim's internal functions like `vim.fn.chansend`, this gets transformed to the text `"v:null"`. Any further processors down the pipeline can't tell the difference between a transformed `nil` value and valid output that contains the text `"v:null"`, so that content is placed into the file as if it were the actual formatter output.
This PR replaces the `nil` with empty output (`{ "" }`) instead.
The expected case where a formatter returns nothing is when the input file is also empty, so this works as expected for that case.
Fixes #241

Don't accept nil as a successful formatter output

---

lua/formatter/filetypes/python.lua

--filename argument should be the exact path to the file. Otherwise, it simply doesn't do anything.

[python] Fix isort

---

lua/formatter/format.lua

This will be helpful when using the format command in lua scripts, allowing fallback behavior, etc.

Make it so that format returns whether or not format task was started

---

lua/formatter/filetypes/nim.lua

Added [nim lang](https://nim-lang.org/) with 2 formatters.
`nimpretty` comes with the nim compiler.
[nph](https://github.com/arnetheduck/nph) is an opinionated formatter.

Add nim lang with formatters nimpretty and nph

---

lua/formatter/filetypes/markdown.lua

Adds the [mdformat](https://github.com/executablebooks/mdformat) markdown formatter.
Tested locally and works just fine. `mdformat` only supports markdown, so I didn't add a `default` entry.

add: mdformat for markdown formatting

---

lua/formatter/defaults/fourmolu.lua
lua/formatter/defaults/ormolu.lua
lua/formatter/defaults/stylish_haskell.lua
lua/formatter/filetypes/haskell.lua

Adding support for other Haskell formatters:
- `ormolu`: https://github.com/tweag/ormolu
- `fourmolu`: https://github.com/fourmolu/fourmolu
Also moved the defaults of `stylish-haskell` to its own defaults file.

add Haskell formatters ormolu and fourmolu

---

lua/formatter/defaults/mixformat.lua

mix formatter need `--stdin-filename`  for heex files. see https://github.com/elixir-lang/elixir/pull/11822
Fixes https://github.com/mhartington/formatter.nvim/issues/206

Fix elixir/heex formatter

---

lua/formatter/filetypes/python.lua

Add a second formatter based on ruff for Python which formats only 
imports. This is different from the current ruff formatter which 
formats everything except imports. Therefore, users will have the
flexibility to format either everything, only imports, or everything
except imports based on the (ruff) formatter(s) they select.

feat(python): add a formatter using ruff to sort imports

---

lua/formatter/util.lua

resolves #305 and #328
The errors documented in the above issues came from the line ranges of the document conflicting with what formatter.nvim saw. It would often happen on newly created empty buffers, which had lines added to them, which were then attempted to be formatted (i.e. before saving, closing and reopening the buffer, in which case the error would not occur).
The error was being returned by the `nvim_buf_get_lines` api call, which was set to strict indexing.
This PR changes ignores strict indexing, which is in keeping with the current approach already implemented in the `nvim_buf_set_lines`.
I therefore thought it was an idiomatic approach given this code base.
In general I also think it's acceptable to ignore this error as the formatting calls always operate on the whole …

fix: error, index out of bounds (get_lines)

---

lua/formatter/init.lua

This allows to call setup multiple times e.g. to add formatters separately
I need this for a plugin of mine (https://github.com/max397574/typst-tools.nvim) where I want to add a new formatter
@mhartington would be really nice if this could get merged soon because this currently is completely blocking work on my new plugin

feat: don't overwrite previous config

---

lua/formatter/filetypes/go.lua

The goimports-reviser has some parameters that control the formatting behavior, and everyone may have different needs.

feat:add params to goimports-reviser
