mhartington/formatter.nvim

lua/format/formatter.lua
lua/format/init.lua
lua/format/util.lua

Only write format output to the buffer when there are no unsaved changes or `Format` was called with bang
I added `force` as a new param for now, but when we want to add more stuff, it'll probably be nicer to have a config table or similar.

Use bang as force write

---

README.md

This PR add some documentation on how to create a autocmd to format the file on save.

docs: add docs for format on save

---

plugin/formatter.vim

Allow "|" after the commands to chain them

---

CONFIG.md

Just a small formatting change :)

Fix dart example

---

CONFIG.md

fix: config documentation

---

CONFIG.md

this PR adds config on how to setup formatter with prisma files if you built `prisma-fmt` from [source](https://github.com/prisma/prisma-engines)

add prisma-fmt in CONFIG.md

---

README.md

update `README.md` and `CONTRIBUTING.md`

Update readme contributing

---

lua/formatter/format.lua

Support skipping a formatter by returning nil

---

lua/formatter/config.lua

fix(): empty formatter array

---

lua/formatter/defaults/fishindent.lua
lua/formatter/filetypes/fish.lua

Hello. I was trying to work with fish files and it gives me pain to indent files from the shell every time. If there is someone who tries to format fish files, I hope this helps them 😄

Add fish_indent support

---

lua/formatter/defaults/init.lua
lua/formatter/filetypes/init.lua

fix format

---

lua/formatter/format.lua

Check buffer validness to mute nvim_buf_get_changedtick error 

---

lua/formatter/filetypes/go.lua

Add the `golines` formatter to the filetype configs.

feat(golines): add golines formatter

---

lua/formatter/defaults/mixformat.lua
lua/formatter/filetypes/elixir.lua

Support for the elixir formatter through `mix format`

Add mix format support

---

README.md
doc/formatter.txt
lua/formatter/format.lua
plugin/formatter.vim

This has been discussed in #131 and #109 so I suggest just ripping the bandaid and calling the thing `FormatLock` and `FormatWriteLock`.
I'll close the other ones and keep this one open for a week or two in case anyone has any major complaints.

Format lock

---

lua/formatter/filetypes/sql.lua

Setting up a new filetype for SQL and adding the `pg_format` formatter.

feat(sql): add pg_format for sql files

---

lua/formatter/filetypes/yaml.lua

Just add a default conf for [yamlfmt](https://github.com/google/yamlfmt).

Create conf for yamlfmt

---

lua/formatter/filetypes/lua.lua

Formatting using lua-format did not work without input file to format

Fix lua-format args

---

lua/formatter/filetypes/ruby.lua

Add configuration for standardrb

---

lua/formatter/filetypes/terraform.lua

Add `terraform fmt` formater for Terraform file type.

feat: add terraform fmt formatter

---

lua/formatter/util.lua

This PR adds a function which returns all available (meaning valid) formatters for a given filetype
I don't have much experience with Lua, so please feel free to ask for changes.

feat(util): get available formatters for a filetype

---

lua/formatter/defaults/biome.lua
lua/formatter/defaults/rome.lua
lua/formatter/filetypes/javascript.lua
lua/formatter/filetypes/javascriptreact.lua
lua/formatter/filetypes/json.lua
lua/formatter/filetypes/typescript.lua
lua/formatter/filetypes/typescriptreact.lua

Add the ~rome~ biome formatter, tested on Arch Linux

feat: Add biome formatter

---

lua/formatter/filetypes/python.lua
lua/formatter/filetypes/toml.lua

Changed python and toml formatters

Added various filename args

---

lua/formatter/filetypes/cs.lua

Adds [csharpier](https://csharpier.com/) as a formatter configuration

feat: add csharpier as formatter configuration

---

lua/formatter/filetypes/java.lua

Add google-java-format formatter

Add google-java-format

---

lua/formatter/defaults/perltidy.lua
lua/formatter/filetypes/perl.lua

Tested using OpenBSD 7.3-current and neovim 0.9.1.

feat(formatter): add perltidy

---

lua/formatter/filetypes/tex.lua

Support for the [latexindent](https://www.ctan.org/pkg/latexindent) formatter for `tex` filetypes.

feat(latexindent): support latexindent formatter for LaTeX

---

lua/formatter/filetypes/zsh.lua

Add beautysh formatter, tested on arm64

feat: Add zsh formatting support

---

lua/formatter/filetypes/templ.lua

Add templ filetype configurations with `templ fmt`.

feat: add templ filetype default configurations

---

lua/formatter/filetypes/vue.lua

Allow using `prettierd` for vue filetype

Add prettierd support for vue

---

lua/formatter/filetypes/crystal.lua

A formatter for crystal lang that comes with the compiler
https://crystal-lang.org/reference/1.12/man/crystal/index.html#crystal-tool-format

Add crystal lang filetype formatter

---

lua/formatter/defaults/ocamlformat.lua

The current config for `ocamlformat` does not work. This should do it.

Fix ocamlformat

---

lua/formatter/filetypes/solidity.lua

Added solidity file type configuration
Related to #308

Add Solidity File Type
